language: c

compiler:
    - gcc

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - gcc-5
      - libboost-dev

before_script:
    - uname -a
    - printenv
    - doxygen --version
    - gcc-5 --version
    - gprof --version
    - grep "#define BOOST_VERSION " /usr/include/boost/version.hpp

script:
    - date
    - ls -al
    - make lc3bAssembler
